### ISSUE TITLE
How to use your tools for medium size objects with an average diameter of 1.5 meter?

### ISSUE THREAD

**Issue by monajalal** [markus-suchi/3D-DAT#8]
In your README, you have stated "annotate poses of objects within a table top scene". Is there any opportunity to use your GUI/tool for medium size objects with an average diameter of 1.5 meter? If not, will you please be able to provide some suggestion in that end?

**Comment by jibweb** [comment]
Hello Mona,
The setup was tested on tabletop scenes, but isn't limited to scenes of a given size. The main requirement is to have multiple views with known camera poses of a given scene, and CAD models of rigid objects to place in the 3D scene. With those two things, any scene can be annotated in principle, but it is important to note that the annotation will be easier the more view coverage you have of your scene (seeing the object from every side will guarantee a higher accuracy pose annotation).

We are currently working on an extension for deformable objects annotation that would not require CAD models for annotation (but still require camera pose) but it is not ready yet.
